# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
# Mario: The branch of the repository where the pipeline is executed. Master branch.
- master
# If I write 
#     - something 
#it will execute in something branch

#Where it's going to execute
pool:
  vmImage: 'ubuntu-latest'    #Ubuntu latest version


container: mcr.microsoft.com/dotnet/core/sdk:3.0

steps:
- task: DotNetCoreCLI@2
  inputs: 
    command: build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests*.csproj'

